In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Neden NumPy ?

In [9]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

a*b

array([ 2,  6, 12, 20])

**Görüldüğü üzere iki vektörün çarpılasmı işlemi numpy arrayleri ile çok daha pratik ve etkili sonuç vermektedir. Numpy kütüphanesi bizi
komplek işlemlerden ve karmaşıklıktan kurtarır** **Bu pratik yaklaşım belki bu gibi kolay problemlerde pek fark yaratmayabilir ama ileride oluşturacağımız işlemlerde bu kütüphane bize çok fazla kolaylık sağlayacaktır**

**Ayrıca yer tutma maliyetleri de numpy arrayleri listelere göre en az 4 kat daha azdır. Demek istediğimiz şu liste veri yapılarında listenin içindeki her elemanın veri yapısı ayrı ayrı depolanır. Yani listenin içindeki her elemanın "int", "str", "float" mu hangi yapıda olduğu tek tek sorgulanır ve hepsi saklanır. Fakat numpy arraylerinde hepsi bir np.array tipinde olarak saklanır ve buna izin verilir. Yani performans olarakta veri depolarında kapladığı alan olarakta numpy arraylerin daha kullanışlı olduğu kesindir**

**Özetlemek gerekirse Neden NumPy sorusunun cevabı iki şekildedir. Bir yazılım anlamında daha optimize edilmiş, daha performanslı, daha düşük maliyetli bir saklama, depolama imkanı sunar. İkinci olarak ise matematiksel anlamda, high level işlemler, vektörel operasyonlara, matris işlemlerine ve matematiksel işlemlere imkan sağlar.**

 ## Numpy Array'i Oluşturmak
 Numpy arraylerini sıfırdan da oluşturabiliriz, listeler ile de oluşturabiliriz

In [11]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
a = np.array([1,2,3,4,5])

type(a)

numpy.ndarray

**NumPy'ın tek bir veri tipi tutmak istediğinden bahsetmiştik aşağıda bunun örneğini görüyoruz, bir tane float değer olursa tüm verileri float'a çeviriyor. Biz bir argüman girerek bu durumu değiştirebiliriz. Bu argüman "dtype"tır**

In [18]:
b = np.array([3.14, 4, 2, 13])
b

array([ 3.14,  4.  ,  2.  , 13.  ])

In [19]:
c = np.array([3.14, 4, 2, 13], dtype ="float32")
c

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [20]:
d = np.array([3.14, 4, 2, 13], dtype ="int")
d

array([ 3,  4,  2, 13])

### Sıfırdan array oluşturma 
**Tek boyutlu array'ler Vektördür, iki boyutlu arrayler matristir**

In [27]:
np.zeros(10, dtype = int) # 10 tane sıfırlardan oluşan array oluşturma fonskiyonu

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.ones((3, 5), dtype = int) # 3x5'lik yani 3 satır 5 sütundan oluşan, ve tüm elemanları 1 olan bir array oluşturmak, matris oluşturma fonksiyonu

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.full((3, 5), 3) # Bizim vermiş olduğumuz boyut bilgisiyle 3'lerden oluşan bir matris, bir array oluşturma fonksiyonu (istediğimiz sayıdan oluşturabiliriz)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [30]:
np.arange(0, 31, 3) # 0'dan 31'e kadar 3'er 3'er artacak şekilde tek boyutlu doğrusal bir array, vektör oluşturmak

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [31]:
np.linspace(0, 1, 10) # iki değer arasında belirli sayıda değer oluşturma, 0 ile 1 arasında 10 tane değer oluştur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [33]:
np.random.normal(10, 4, (3,4)) # ortalaması 10, standart sapması 4 olan 3x4'lük normal dağılan bir matris oluşturır, rastgele sayılardan oluşacak şekilde

array([[14.31234251, 17.69960048,  6.01542918,  8.7733239 ],
       [13.88059205, 11.04109457, 11.44638656, 11.49168717],
       [ 6.48204708, 12.20418637, 10.27048952, 11.57951042]])

In [34]:
np.random.randint(0, 10, (3,3)) # 0 ile 10 arasında 3x3'lük rastgele int değerlerden oluşan matris oluiturma

array([[9, 9, 1],
       [2, 3, 2],
       [8, 2, 3]])

## Temel Özellikleri
* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [37]:
a = np.random.randint(10, size = 10)
a

array([9, 1, 4, 9, 9, 4, 3, 8, 9, 7])

In [39]:
a.ndim # a değişkeninin boyutunu gösterdi

1

In [40]:
a.shape # boyut bilgisini verdi, 1 boyutlu olduğu için o boyutun bilgisi gösterildi, o boyutta 10 eleman var olarak gösteri

(10,)

In [42]:
a.size # toplam eleman sayısını verdi

10

In [44]:
a.dtype # data tipini verdi

dtype('int32')

Farklılıkları görmek için 2 boyutlu bir array oluşturup onu da inceleyelim

In [45]:
b = np.random.randint(10, size =(3,5))
b

array([[8, 6, 8, 9, 4],
       [8, 8, 2, 6, 3],
       [1, 6, 8, 1, 0]])

In [46]:
b.ndim

2

In [47]:
b.shape

(3, 5)

In [48]:
b.size

15

In [49]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme (reshaping)

In [50]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b = a.reshape((1,9))

In [57]:
a.ndim, b.ndim

(1, 2)

## Array Birleştirme (Concatenation)

In [58]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [59]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [60]:
z = np.array([7,8,9])

In [61]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# ihi noyut

a = np.array([[1,2,3],
              [4,5,6]])

In [63]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
np.concatenate([a,a], axis=1) # sütun bazında birleştirme

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [66]:
x = np.array([1,2,3,99,99,3,2,1])

In [73]:
np.split(x, [3,5]) # x'i ayır, 3ten 5^e kadar

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [74]:
a,b,c = np.split(x, [3,5])
a

array([1, 2, 3])

In [75]:
b

array([99, 99])

In [76]:
c

array([3, 2, 1])

In [77]:
# iki boyutlu ayırma

In [78]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [87]:
ust, alt = np.vsplit(m, [2])

In [81]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# diker olarak bölme

In [83]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [84]:
sag, sol = np.hsplit(m, [2])

In [85]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [86]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [88]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [91]:
np.sort(v), v # NumPy kütüphanesi içindeki sort() metodu asıl değişkeni değiştirmez fakat python içindeki sort() metodu asıl değişkeni değiştirir

(array([1, 2, 3, 4, 5]), array([2, 1, 4, 3, 5]))

In [93]:
v.sort(), v

(None, array([1, 2, 3, 4, 5]))

In [95]:
# İki boyutta sıralama

In [97]:
m = np.random.normal(20, 5, (3,3))
m

array([[30.29836289, 18.55679611, 24.30969471],
       [13.87400666, 31.00143022, 22.26935459],
       [12.84485505, 24.01151628, 13.95253546]])

In [100]:
np.sort(m, axis = 1) # satıra göre sıralama

array([[18.55679611, 24.30969471, 30.29836289],
       [13.87400666, 22.26935459, 31.00143022],
       [12.84485505, 13.95253546, 24.01151628]])

In [101]:
np.sort(m, axis = 0) # sütuna göre sıralama

array([[12.84485505, 18.55679611, 13.95253546],
       [13.87400666, 24.01151628, 22.26935459],
       [30.29836289, 31.00143022, 24.30969471]])

## Alt Küme Üzerinde İşlem Yapmak

In [108]:
a = np.random.randint(10, size =(5,5))
a

array([[9, 5, 3, 4, 6],
       [8, 9, 7, 6, 2],
       [3, 3, 0, 8, 5],
       [9, 0, 6, 7, 7],
       [9, 7, 5, 9, 4]])

In [109]:
alt_a = a[0:3, 0:2]
alt_a

array([[9, 5],
       [8, 9],
       [3, 3]])

In [112]:
alt_a[0,0] = 999 # Görüldüğü üzere alt küme üzerinde yaptığmız değişken ataması, orjinal a değişkenimizi de değiştirdi.
alt_a[1,1] = 888

alt_a, a

(array([[999,   5],
        [  8, 888],
        [  3,   3]]),
 array([[999,   5,   3,   4,   6],
        [  8, 888,   7,   6,   2],
        [  3,   3,   0,   8,   5],
        [  9,   0,   6,   7,   7],
        [  9,   7,   5,   9,   4]]))

**Bu tarz problemleri yaşamamak için copy() metodunu kullanacağız ve bir kopyada işlemlerimiz gerçekleşecek**

In [113]:
b = np.random.randint(10, size =(5,5))
b

array([[9, 3, 9, 9, 2],
       [6, 1, 9, 4, 8],
       [7, 5, 3, 8, 2],
       [6, 9, 9, 9, 2],
       [8, 4, 6, 0, 5]])

In [114]:
alt_b = b[0:3, 0:2].copy()
alt_b

array([[9, 3],
       [6, 1],
       [7, 5]])

In [115]:
alt_b[0,0] = 999
alt_b, b

(array([[999,   3],
        [  6,   1],
        [  7,   5]]),
 array([[9, 3, 9, 9, 2],
        [6, 1, 9, 4, 8],
        [7, 5, 3, 8, 2],
        [6, 9, 9, 9, 2],
        [8, 4, 6, 0, 5]]))

## Fancy Index ile Elemanlara Erişmek

In [116]:
import numpy as np

v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [120]:
v[1], v[3], v[5]

(3, 9, 15)

In [122]:
al_getir = [1, 3, 5]

v[al_getir]

array([ 3,  9, 15])

In [123]:
# iki boyutta fancy indexing

In [124]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
satir = np.array([0,1])
sutun = np.array([1,2])

m[satir, sutun]

array([1, 5])

In [126]:
# basit indeks ile fancy indeks

In [127]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
m[0, [1,2]]

array([1, 2])

In [129]:
# slice

In [130]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu Eleman işlemleri

In [131]:
v = np.array([1,2,3,4,5])

In [132]:
v < 3

array([ True,  True, False, False, False])

In [134]:
v[v < 3] # sadece true olan değerleri çıkardı

array([1, 2])

In [135]:
v[v >= 3]

array([3, 4, 5])

In [137]:
v[v == 3]

array([3])

In [138]:
v[v != 3]

array([1, 2, 4, 5])

In [139]:
v

array([1, 2, 3, 4, 5])

In [140]:
v * 2

array([ 2,  4,  6,  8, 10])

In [141]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [142]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [143]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Matematiksel İşlemler

In [144]:
v = np.array([1,2,3,4,5])

In [145]:
v - 1 

array([0, 1, 2, 3, 4])

In [146]:
v * 5

array([ 5, 10, 15, 20, 25])

In [147]:
v / 5 

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [148]:
v *5/10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [149]:
# ufunc

In [151]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [152]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [153]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [154]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [155]:
np.power(v, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [157]:
np.mod(v, 2) # v % 2 'nin karşılığı, ufunc

array([1, 0, 1, 0, 1], dtype=int32)

In [158]:
np.absolute(np.array([-7]))

array([7])

In [159]:
np.sin(360)

0.9589157234143065

In [160]:
np.cos(180)

-0.5984600690578581

In [161]:
v = np.array([1,2,3])

np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [162]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [163]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

## NumPy ile İki Bilinmeyenli Denklem Çözümü

In [165]:
import numpy as np

**5*x0 + x1 = 12**<br>
**x0 + 3*x1 = 10**<br>
**Çözüm Kümesi Nedir ?**

In [167]:
a = np.array([[5,1],[1,3]]) # katsayılarımız
b = np.array([12,10]) # Çözüm Kümemiz

In [169]:
a, b

(array([[5, 1],
        [1, 3]]),
 array([12, 10]))

In [171]:
x = np.linalg.solve(a, b) # x0 ve x1 değerlerini bul
x

array([1.85714286, 2.71428571])

**Sağlamasını yapmamız gerekirse ikinci denklemi -5 ile çarpıp taraf tarafa toplama yaparsak x1 değerini bulacağız. Bunu da gerçekleştirelim**

In [178]:
ıkıncı_denklem_carpilmis = a[1] * -5, b[1] * -5
ıkıncı_denklem_carpilmis

(array([ -5, -15]), -50)

In [180]:
birinci_denklem = a[0], b[0]
birinci_denklem

(array([5, 1]), 12)

In [183]:
# -14x1 = -38 denklemini elde ederiz x1'de burdan 2.714 hesaplanır

In [184]:
-38/-14

2.7142857142857144

**Görüldüğü gibi x1 değeri fonksiyonumuzun sonucuyla aynı çıktı sağlamamız sayesinde doğru sonucu elde ettiğimizden emin oluyoruz**